name: qr_system
description: "Aplicación Flutter para Sistema de Gestión de Objetos con QR."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI / utilidades
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  intl: ^0.19.0

  # HTTP
  http: ^1.1.0

  # State management
  provider: ^6.0.0

  # Local storage
  shared_preferences: ^2.2.0

  # QR Scanner
  mobile_scanner: ^4.0.0

  # Imagen (GALERÍA / CÁMARA)
  image_picker: ^1.0.4

  # Archivos / rutas
  path_provider: ^2.1.1

  # JSON
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icono.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icono.png"